### ISSUE TITLE
Populate dashboard context with club data

### ISSUE THREAD

**Issue by serenalau272** [UoaWDCC/wdcc-clubs-mem-checker#105]
Note: Already half done

### Acceptance Criteria
- [x] When the cached club changes, the #104 should be called to fetch the data for that club
- [x] The data returned for that club should all be stored in the context on the root dashboard component
- [ ] get admins from endpoint #110 
- [ ] get club size from endpoint #110

**Comment by serenalau272** [comment]
Completed as part of #106
