### ISSUE TITLE
Demo 1 To-Do

### ISSUE THREAD

**Issue by serenalau272** [UoaWDCC/wdcc-clubs-mem-checker#32]
#### Tuesday
- [x] #15
- [x] #13 
- [x] #19 

#### Tuesday
- [x] Route '/sign-in/no-clubs' to '/create-club' or '/invite-code' @alexwillmcleod
- [ ] Route '/create-club' and '/invite-code' back to '/signIn/no-clubs' @alexwillmcleod
- [ ] Route '/create-club' to '/create-page' @Alam624 
- [x] Route '/invite-code' to '/dashboard' @wsee046 

#### Wednesday
- [ ] Hook up enter invite code with the Verify Invite code endpoint @wsee046 @Alam624   
  - [ ] Error message if invite code invalid
#### Thursday
- [x] Hook up spreadsheet ID + sheet tab ID with get columns endpoint @wsee046
  - [x] Error message if invalid sheet
