### ISSUE TITLE
Confirm customisations component

### ISSUE THREAD

**Issue by serenalau272** [UoaWDCC/wdcc-clubs-mem-checker#50]
### Description
As an `event creator`, I want to `have the opportunity to double-check my customisation selections` so that `I can minimise human errors`.

### Acceptance Criteria
- [x] Users are presented with text asking them to confirm their customisations
- [x] Next button sends a request to #22 create the club checker page using the customisations stored in the frontend context
- [x] After the page has been created and the pathID has been returned, component routes to #7 and passes the pathID as a navigation param
- [x] Back button routes back to #49 

https://stackoverflow.com/questions/42173786/react-router-pass-data-when-navigating-programmatically
