### ISSUE TITLE
Cosmetic Fixes

### ISSUE THREAD

**Issue by serenalau272** [UoaWDCC/wdcc-clubs-mem-checker#76]
```[tasklist]
### To-do Fixes
- [ ] Responsiveness
- [ ] Button size consistency
- [ ] Scroll bar styling
- [ ] Add loading icons everywhere
- [ ] #21 Left-align the column selector list
- [ ] #21  Default column selector dropdown on top of the column list
- [ ] #21 DIsplay selected default column name i.e. 'Default: <column-name>'
- [ ] #45  Add default page title to the page title component
- [ ] #46  Selected font is not persisted
- [ ] #47 Fix up positioning and dark text fields and remove user selection
- [ ] Confirmation page background colour of first render
```
